name: Deploy lgn_server_frontend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: | npm install

      - name: Build project
        run: | npm run build

      - name: Deploy to EC2
        env:
          EC2_USER: ubuntu
          EC2_HOST: ec2-52-66-253-179.ap-south-1.compute.amazonaws.com
          PROJECT_DIR: /home/ubuntu/lgn_server_frontend
          WEB_DIR: /var/www/html/lgnsf
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
            cd ${{ env.PROJECT_DIR }} || { echo "Directory not found"; exit 1; }
            git pull origin master || { echo "git pull failed"; exit 1; }
            npm install || { echo "npm install failed"; exit 1; }
            npm run build || { echo "npm run build failed"; exit 1; }
            sudo chown -R $USER:www-data ${WEB_DIR}
            sudo chmod -R 775 ${WEB_DIR}
            sudo cp -r ${{ env.PROJECT_DIR }}/build/* ${WEB_DIR}/ || { echo "File copy failed"; exit 1; }
            sudo chown -R www-data:www-data ${WEB_DIR}
            echo "Deployment successful"
          EOF
