name: React.js Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        project:
          - name: lgn_user_frontend
            web_dir: /var/www/html
          - name: lgn_server_frontend
            web_dir: /var/www/html/lgnsf

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd ${{ matrix.project.name }}
        npm install

    - name: Build project
      run: |
        cd ${{ matrix.project.name }}
        CI=false npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.project.name }}
        path: ${{ matrix.project.name }}/build

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - name: lgn_user_frontend
            web_dir: /var/www/html
          - name: lgn_server_frontend
            web_dir: /var/www/html/lgnsf

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-${{ matrix.project.name }}
        path: build

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      env:
        EC2_USER: ubuntu
        EC2_HOST: ec2-13-201-10-194.ap-south-1.compute.amazonaws.com
        WEB_DIR: ${{ matrix.project.web_dir }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
          echo "Connecting to EC2 instance for ${{ matrix.project.name }}"
          cd /home/ubuntu/${{ matrix.project.name }} || { echo "Directory not found"; exit 1; }
          echo "Setting directory permissions"
          sudo chown -R $USER:$USER /home/ubuntu/${{ matrix.project.name }}
          echo "Pulling latest code from GitHub"
          git pull origin master || { echo "git pull failed"; exit 1; }
          echo "Installing dependencies"
          sudo npm install || { echo "npm install failed"; exit 1; }
          echo "Building project"
          sudo npm run build || { echo "npm run build failed"; exit 1; }

          echo "Copying files to $WEB_DIR"
          sudo rm -rf $WEB_DIR/*
          sudo cp -r /home/ubuntu/${{ matrix.project.name }}/build/* $WEB_DIR/ || { echo "File copy failed"; exit 1; }
          echo "Deployment successful for ${{ matrix.project.name }}"
        EOF
